; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_nrf52840_sense]
platform = nordicnrf52
board = adafruit_feather_nrf52840_sense
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
board_upload.wait_for_upload_port = false
build_flags = 
	-I"$PROJECT_LIBDEPS_DIR/$PIOENV/Adafruit SPIFlash/src"
	-DUSE_TINYUSB
lib_deps = 
	symlink:///Users/austin/Library/Arduino15/packages/adafruit/hardware/nrf52/1.7.0/libraries/Adafruit_TinyUSB_Arduino
	symlink:///Users/austin/Library/Arduino15/packages/adafruit/hardware/nrf52/1.7.0/libraries/SPI
	adafruit/Adafruit TinyUSB Library@^3.7.7
	adafruit/SdFat - Adafruit Fork@^2.3.103
	bblanchon/ArduinoJson@^7.2.2
	adafruit/Adafruit SPIFlash@^5.1.1
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit Sensor Calibration@^1.1.5
	adafruit/Adafruit AHRS@^2.4.0
